### ISSUE TITLE
Recent commit causes issues on Windows, macOS and Linux

### ISSUE THREAD

**Issue by leonstyhre** [sammycage/lunasvg#131] opened 2023-05-08 18:39 UTC
Hi!

The commit b7e72fb377084883f9e672c045c91428860f9f20 breaks my build with LunaSVG on Windows as the .dll file is now placed inside a bin subdirectory and the .lib file inside a lib subdirectory instead of being saved to the root of the build tree as was previously the case.

Would it be possible to revert to the previous locations so builds continue to work as before?
Thanks!

**Comment by sammycage** [comment] 2023-05-08 21:58
@seanharmer?

**Comment by sammycage** [comment] 2023-05-08 21:59
#84

**Comment by seanharmer** [comment] 2023-05-09 09:17
Could you elaborate on what you mean by "breaks my build" please? What precisely breaks?

**Comment by leonstyhre** [comment] 2023-05-10 17:30
Hi, any news regarding this?

Unfortunately the ES-DE AUR release is already broken on Arch Linux as it now uses GCC 13. This means that it already affects a number of users that can't update or install my application. To fix that I need commit db27b7c0ef987f222a87e24f4feec507cfe9635d but I can't update to that, as the commit discussed in this issue breaks the build.

I would really need a fix as soon as possible so that I can make it possible to build ES-DE on Arch Linux again. As described I need the artifacts to end up in the root of the repository and not in subdirectories.
Thanks!

**Comment by sammycage** [comment] 2023-05-10 18:40
Did this commit https://github.com/sammycage/lunasvg/commit/db27b7c0ef987f222a87e24f4feec507cfe9635d break the build as well? I will look into this issue in a month's time; I am kind of busy right now.

**Comment by leonstyhre** [comment] 2023-05-10 18:55
No it's the CMake change that breaks the build:
b7e72fb377084883f9e672c045c91428860f9f20

```
- if(BUILD_SHARED_LIBS)
-     target_compile_definitions(lunasvg PUBLIC LUNASVG_SHARED)
-     target_compile_definitions(lunasvg PRIVATE LUNASVG_EXPORT)
+ set_target_properties(lunasvg
+     PROPERTIES
+     ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
+     LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
+     RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin"
```

LunaSVG itself compiles but liblunasvg.a (and .dll and .lib) ends up in subdirectories as you can see above.

I can't wait a month, I can't even wait a day really as my application now can't be installed via the AUR. So it affects production right now. If you don't have time then please simply revert the CMake patch and everything should work correctly again.

**Comment by sammycage** [comment] 2023-05-10 20:10
Okay, I understand your point now. However, it seems like a personal issue. Maybe you should try using the following command in order to address the problem:

```
cmake -B <build_directory> -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=<archive_output_directory> -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=<library_output_directory> -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=<runtime_output_directory> <path_to_source>
```

This command can help you specify the desired output directories for your build process.

**Comment by leonstyhre** [comment] 2023-05-11 15:18
What you propose will not work, but the following workaround/override does work:

```
add_subdirectory(lunasvg EXCLUDE_FROM_ALL)

set_target_properties(lunasvg
    PROPERTIES
    ARCHIVE_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}
    LIBRARY_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}
    RUNTIME_OUTPUT_DIRECTORY ${PROJECT_SOURCE_DIR}
)
```

That's in my CMakeLists.txt file so I can do this without touching the LunaSVG subtree.

It's however very crazy that I need to do this, on Unix/Linux and macOS I build using static linking and I can't believe anyone would want to have the liblunasvg.a file in a lib subdirectory, you want to have all artifacts in the same build directory when compiling libraries in-tree as many projects do. All other libraries behave this way and LunaSVG did as well prior to the commit discussed in this issue.

If using dynamic linking like I do on Windows it's even worse as the application will not run from the build directory as the .dll file is not in the same directory as the application binary. That makes it impossible to debug for example, again I can't understand why anyone would want that behavior.

But as the workaround described above solves the problem for me on all supported platforms it's a non-issue for me now. It will however be very confusing for anyone else that attempts to build in-tree using your library, unless they find this issue of course and can read about the workaround.

Btw, this still does not solve the MSVC compiler warnings mentioned in a previous comment, but since I only use MSVC for testing and debugging and make all releases using MinGW this is not a practical problem for me and like mentioned in a previous comment I don't even understand exactly what the message means anyway and what is its implications.

With all this said I'll now be able to at least make my application compile correctly with GCC 13 so the urgent issue will be resolved.

**Comment by sammycage** [comment] 2023-05-26 09:41
Hey @leonstyhre, 

I apologize for the delay in reverting the commit. I understand that the issue with the CMake not working for you is causing inconvenience. I've reached out to @seanharmer regarding this matter, but unfortunately, I haven't received a response from him yet.

In order to ensure stability and functionality for everyone, I have decided to revert the commit for now. Rest assured, I will personally take responsibility for modernizing the CMake build as soon as I have the time to do so. 

Thank you for bringing this issue to my attention, and I apologize again for any inconvenience caused. If you have any further concerns or questions, please let me know.

Best regards,
Samuel Ugochukwu

**Comment by lcgamboa** [comment] 2023-05-26 12:23
Hi @sammycage,

Now my projects build scripts and github CI are broken again. When there was the first change in Cmake files I simply updated all the scripts on  my projects to fetch the library in the new path and everything worked normally. Now I have to undo everything because someone else can't set up their own project. I hope there are no more such changes. I personally do not agree with this regression.

**Comment by leonstyhre** [comment] 2023-05-26 16:43
Thanks @sammycage for reverting the commit and for looking into modernizing the configuration in a more non-disruptive manner.

To clarify though I did manage to get my application to build with the problematic CMake changes using the workaround described in an earlier comment. I will probably await your planned CMake updates before pulling any further LunaSVG updates into my project so I don't need to change my CMake configuration twice more. At the moment it's working fine so there's no urgency when it comes to this for my project at least (I'm using LunaSVG as a subtree and only pull upstream updates manually when needed).

Thanks as always for your excellent support and for your very nice SVG library.

**Comment by dg0yt** [comment] 2023-05-31 07:32
Hm, reverting the whole change, including the exported CMake config, seem quite a big step back just to restore build-internal target properties. The broken use case was tight coupling, and the CMake config is the enable for loose coupling.

**Comment by dg0yt** [comment] 2024-01-03 05:32
Do I understand correctly that there is no progress with regard to exported CMake config?

**Comment by dg0yt** [comment] 2024-08-23 05:14
It is a pity that there was no communication here. 
When I did my last post, I was about to update the vcpkg port to 2.4.0. I see that I didn't complete this. Now there is 2.4.1 without CMake config improvement, and master is switched to meson. Feeling discouraged now.

**Comment by sammycage** [comment] 2024-08-23 06:19
@dg0yt I apologize for any frustrations caused by the lack of communication. I appreciate the effort you put into updating the vcpkg port. I will move the current master to another branch and ensure that the CMake configuration issue is addressed in version 2.4.1. Would that be acceptable to you?

**Comment by dg0yt** [comment] 2024-08-23 06:29
Thanks for the response. 

I don't want to ask for changes for master if the decision for meson has been made already. vcpkg can handle mesong. But for people using CMake's `FetchContent`, git submodules or similar, this will be much more disruptive than the reasons for reverting https://github.com/sammycage/lunasvg/commit/b7e72fb377084883f9e672c045c91428860f9f20, the original issue here. And AFAIK meson has no support for generating CMake config. (And Visual Studio users might want multi-config usage.)

Let's turn it around: 
Do you need help with CMake config? In vcpkg it is available but prefixed "unofficial" because it not from here.
Do you need help providing pkg-config files from CMake?

**Comment by sammycage** [comment] 2024-08-23 07:12
> But for people using CMake's FetchContent, git submodules or similar, this will be much more disruptive than the reasons for reverting b7e72fb, the original issue here.

I understand your concern. However, I did put out a notice about transitioning to Meson two months ago, and there were no complaints at that time. #170 

> Do you need help with CMake config? In vcpkg it is available but prefixed "unofficial" because it not from here. Do you need help providing pkg-config files from CMake?

Thank you for offering help. We appreciate it. However, we are not planning to revert to CMake. My intention was only to address the issues in version 2.4.1 for those who might still want to use it.

**Comment by dg0yt** [comment] 2024-08-23 10:46
> > But for people using CMake's FetchContent, git submodules or similar, this will be much more disruptive than the reasons for reverting [b7e72fb](https://github.com/sammycage/lunasvg/commit/b7e72fb377084883f9e672c045c91428860f9f20), the original issue here.
> 
> I understand your concern. However, I did put out a notice about transitioning to Meson two months ago, and there were no complaints at that time. #170

Well, I'm subscribed to *this* issue, and I was totally unaware of #170 until you touched this issue. Maybe that's also the situation for others. They will notice when they try to update. (Same pattern as this issue.) A deprecation warning in 2.4 release notes might have invited more feedback.

FTR I just checked the README's list Projects Using LunaSVG, and at least half of them use CMake. I didn't check how they integrate LunaSVG.

> > Do you need help with CMake config? In vcpkg it is available but prefixed "unofficial" because it not from here. Do you need help providing pkg-config files from CMake?
> 
> Thank you for offering help. We appreciate it. However, we are not planning to revert to CMake. My intention was only to address the issues in version 2.4.1 for those who might still want to use it.

The question of offering an installed CMake config is independent of how you build LunaSVG. It can be installed from meson, too. 

pkg-config doesn't fill the gap for C++ libs. At least pc files usually don't pass the link langugage, which is a problem when linking the C++ lib becomes a transitive usage requirement for a static lib with C API. (Example: TIFF (C) can use Lerc (C++).)

**Comment by sammycage** [comment] 2024-08-23 11:04
> The question of offering an installed CMake config is independent of how you build LunaSVG. It can be installed from meson, too.

Okay, that would be very kind of you.

**Comment by MarxLabbis** [comment] 2024-09-30 10:17
It is a pity that there was no communication here. When I did my last post, I was about to update the vcpkg port to 2.4.0. I see that I didn't complete this.

 Now there is 2.4.1 without CMake config improvement, and master is switched to meson. Feeling discouraged now.

Something replayed

> > The question of offering an installed CMake config is independent of how you build LunaSVG. It can be installed from meson, too.
> 
> Okay, that would be very kind of you.



> No it's the CMake change that breaks the build: [b7e72fb](https://github.com/sammycage/lunasvg/commit/b7e72fb377084883f9e672c045c91428860f9f20)
> 
> ```
> - if(BUILD_SHARED_LIBS)
> -     target_compile_definitions(lunasvg PUBLIC LUNASVG_SHARED)
> -     target_compile_definitions(lunasvg PRIVATE LUNASVG_EXPORT)
> + set_target_properties(lunasvg
> +     PROPERTIES
> +     ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
> +     LIBRARY_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/lib"
> +     RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin"
> ```
> 
> LunaSVG itself compiles but liblunasvg.a (and .dll and .lib) ends up in subdirectories as you can see above.
> 
> I can't wait a month, I can't even wait a day really as my application now can't be installed via the AUR. So it affects production right now. If you don't have time then please simply revert the CMake patch and everything should work correctly again.



> > The question of offering an installed CMake config is independent of how you build LunaSVG. It can be installed from meson, too.
> 
> Okay, that would be very kind of you.



> > > But for people using CMake's FetchContent, git submodules or similar, this will be much more disruptive than the reasons for reverting [b7e72fb](https://github.com/sammycage/lunasvg/commit/b7e72fb377084883f9e672c045c91428860f9f20), the original issue here.
> > 
> > 
> > I understand your concern. However, I did put out a notice about transitioning to Meson two months ago, and there were no complaints at that time. #170
> 
> Well, I'm subscribed to _this_ issue, and I was totally unaware of #170 until you touched this issue. Maybe that's also the situation for others. They will notice when they try to update. (Same pattern as this issue.) A deprecation warning in 2.4 release notes might have invited more feedback.
> 
> FTR I just checked the README's list Projects Using LunaSVG, and at least half of them use CMake. I didn't check how they integrate LunaSVG.
> 
> > > Do you need help with CMake config? In vcpkg it is available but prefixed "unofficial" because it not from here. Do you need help providing pkg-config files from CMake?
> > 
> > 
> > Thank you for offering help. We appreciate it. However, we are not planning to revert to CMake. My intention was only to address the issues in version 2.4.1 for those who might still want to use it.
> 
> The question of offering an installed CMake config is independent of how you build LunaSVG. It can be installed from meson, too.
> 
> pkg-config doesn't fill the gap for C++ libs. At least pc files usually don't pass the link langugage, which is a problem when linking the C++ lib becomes a transitive usage requirement for a static lib with C API. (Example: TIFF (C) can use Lerc (C++).)

**Comment by sammycage** [comment] 2024-09-30 12:32
Thanks for your feedback on the recent changes to LunaSVG's build system. I know the switch to Meson has caused some concerns, especially for CMake users.

Good news: we've reinstated the CMake configuration! You can now use command-line options to set your preferred values during the build. This should make things easier for everyone. If you have any more questions or need help, just let me know!

**Closed** 2024-11-03 22:31 UTC
Labels: documentation, enhancement, question, cmake
