### ISSUE TITLE
how to get text node(none element type items)

### ISSUE THREAD

**Issue by zhaoxiangfeng** [sammycage/lunasvg#196] opened 2024-11-07 04:07 UTC
hi:
i load a svg into a document object,and i want to modify some text node object on runtime,to change the text content or it's styles to show on the screen.how to get text node in a document object?
thanks!

**Comment by sammycage** [comment] 2024-11-07 06:09
Hi 👋,

Here’s an example that demonstrates how to change the text content and style of an SVG text node:

```cpp
auto data = R"SVG(
<svg xmlns="http://www.w3.org/2000/svg">
    <text id='a' y='120' font-size='120'>Hello World</text>
</svg>
)SVG";

auto document = Document::loadFromData(data);

auto textElement = document->getElementById("a");
auto textNode = textElement.children().front().toTextNode();
textNode.setData("I love SVG!!!");

document->updateLayout(); 
```

This will change the text content of the text node with `id="a"` to “I love SVG!!!”.

Here’s another example for modifying an SVG element's attributes:

```cpp
auto document = Document::loadFromData("<svg viewBox='0 0 200 200'><circle id='a' cx='50' cy='50' r='40' fill='green'/></svg>");
auto element = document->getElementById("a");
element.setAttribute("cx", "100");
element.setAttribute("cy", "100");
element.setAttribute("r", "100");
element.setAttribute("fill", "red");

document->updateLayout();
```

Reminder: Don’t forget to call `Document::updateLayout` after making modifications to reflect the changes on the screen.

Hope this helps!

**Comment by zhaoxiangfeng** [comment] 2024-11-07 07:54
> Hi 👋,
> 
> Here’s an example that demonstrates how to change the text content and style of an SVG text node:
> 
> ```c++
> auto data = R"SVG(
> <svg xmlns="http://www.w3.org/2000/svg">
>     <text id='a' y='120' font-size='120'>Hello World</text>
> </svg>
> )SVG";
> 
> auto document = Document::loadFromData(data);
> 
> auto textElement = document->getElementById("a");
> auto textNode = textElement.children().front().toTextNode();
> textNode.setData("I love SVG!!!");
> 
> document->updateLayout(); 
> ```
> 
> This will change the text content of the text node with `id="a"` to “I love SVG!!!”.
> 
> Here’s another example for modifying an SVG element's attributes:
> 
> ```c++
> auto document = Document::loadFromData("<svg viewBox='0 0 200 200'><circle id='a' cx='50' cy='50' r='40' fill='green'/></svg>");
> auto element = document->getElementById("a");
> element.setAttribute("cx", "100");
> element.setAttribute("cy", "100");
> element.setAttribute("r", "100");
> element.setAttribute("fill", "red");
> 
> document->updateLayout();
> ```
> 
> Reminder: Don’t forget to call `Document::updateLayout` after making modifications to reflect the changes on the screen.
> 
> Hope this helps!

sammycage:
hi! thank you for you warmly help,it works perfectly!
and thank you for you great work,it manupulate svg file and render it  efficiently.
i use it to render svg file and write the result to a bitmap,then i put it to a dispaly(screen),i change some of it's attributes and make it looks pretty moving and shining.
once again thank you and best regards!

**Comment by zhaoxiangfeng** [comment] 2024-11-13 08:51
Hi @sammycage：
   i want to change the 'class' property to change some graphics's fill color,snippet codes like this:
pSVGElement_circle->setAttribute("class", "red-circle");
pSVGElement_rect->setAttribute("class", "blue-rect");
document->updateLayout();

but it is invalid,how can i make it runing right?
CSS Styles are defined ok,it's running rightly in browser.

thanks and best regards!

**Comment by sammycage** [comment] 2024-11-13 19:31
Hi @zhaoxiangfeng,

Currently, in lunasvg, modifying CSS-related attributes such as `class` or `style` elements doesn’t apply the expected styling changes due to how the library is designed. To help with this, I'm considering adding a method like `document->applyStyleSheet("rect { fill: red; }");`, which would allow you to apply a specified CSS stylesheet directly to the document. This approach could be especially useful for updating the styles of SVG elements in bulk, such as for theme changes.

If this sounds like it would help achieve what you're looking for, please let me know, and I’d be happy to implement it. I'd also be interested to know the purpose or function of lunasvg in your project, if you're open to sharing.

**Comment by zhaoxiangfeng** [comment] 2024-11-14 01:01
> Hi @zhaoxiangfeng,
> 
> If this sounds like it would help achieve what you're looking for, please let me know, and I’d be happy to implement it. I'd also be interested to know the purpose or function of lunasvg in your project, if you're open to sharing.

hi @sammycage:
    exactly,it's very helpful for me.i'm an electricity engineer,and currentlly i'm leaning c/c++ language and try to develop a  application running on a device,the device mornitors  electricity objects such as switch/transformer etc.these objects have some states,when they are runing,stoped,something wrong or out of order,they are in diffrent stages,i want to show these stages using graphics on screen,so i define diffrent css styles in svg file,and i switch the css class type to change the graphics appearance.
   that is my purpose,but i'm not good at software programming,i don't know whether it can be achieved,so your help is really important to me.

thanks and best regards!

**Comment by sammycage** [comment] 2024-11-14 12:02
Hi @zhaoxiangfeng,

Thank you for sharing more about your project—it sounds like you're doing some really interesting work! 

I've gone ahead and added the `applyStyleSheet` function, which should help you achieve the dynamic styling you need for displaying the different states of your electrical objects.

Feel free to contact me via email at sammycageagle@gmail.com. I’d be happy to see how I can support you in achieving this.

Best regards!

**Comment by zhaoxiangfeng** [comment] 2024-11-15 02:23
> Hi @zhaoxiangfeng,
> 
> Thank you for sharing more about your project—it sounds like you're doing some really interesting work!
> 
> I've gone ahead and added the `applyStyleSheet` function, which should help you achieve the dynamic styling you need for displaying the different states of your electrical objects.
> 
> Feel free to contact me via email at [sammycageagle@gmail.com](mailto:sammycageagle@gmail.com). I’d be happy to see how I can support you in achieving this.
> 
> Best regards!

great!
yes,you totally understood what i said!
expecting your great works!

thank you sincerely!

**Comment by sammycage** [comment] 2024-11-17 14:16
@zhaoxiangfeng How is it going? If the update fixed your issue, could you kindly close this issue?

**Comment by zhaoxiangfeng** [comment] 2024-11-18 07:58
> @zhaoxiangfeng How is it going? If the update fixed your issue, could you kindly close this issue?

wow,so quickly...great!
i will test the new feature......

**Comment by sammycage** [comment] 2024-11-18 08:07
I mean if the `applyStyleSheet` function fixed your issue. Let me know how the testing goes!

**Comment by zhaoxiangfeng** [comment] 2024-11-19 00:44
hi @sammycage:
i tested the following codes,it woked very well:
        ......
        const char* css_green = ".green-circle {stroke: #006600;fill: #00cc00; stroke-width:2;stroke-dasharray:5,5;}";
	pElement->setAttribute("class", "green-circle");
        document->applyStyleSheet(css_green);
	document->updateLayout();
the applyStyleSheet function really help me a lot.the question is not a question anymore.

thank you so much!

**Closed** 2024-11-19 00:44 UTC
Labels: documentation, enhancement, question

**Comment by sammycage** [comment] 2024-11-19 09:00
I'm glad to hear that the codes worked well for you and that the `applyStyleSheet` function was helpful!

Just a small note: the line `pElement->setAttribute("class", "green-circle");` is redundant in this case, as the stylesheet itself already defines the styling.

**Comment by zhaoxiangfeng** [comment] 2024-11-20 00:34
> I'm glad to hear that the codes worked well for you and that the `applyStyleSheet` function was helpful!
> 
> Just a small note: the line `pElement->setAttribute("class", "green-circle");` is redundant in this case, as the stylesheet itself already defines the styling.

yes,i have already noticed that,when i comment out that line of code,it work good as well.
next i want to package this function to a new function,when i set "class" property value,
the new function will get the css text and call the stylesheet function.
all the css text will be cached when load the svg file into a document.

the stylesheet function is realy a flexible function and easy to use,if i embed a javascript engine into my app,
i call javascript engine to execute a js function to modify the css text and pass that text to stylesheet function,
then maybe i can get a animation function,but i have lots of knowlege to learn and the way is long to go.
thank you for you warmly help and supports!

best regards!

**Comment by zhaoxiangfeng** [comment] 2024-11-22 06:37
hi @sammycage :
the transform function in a css text is not valid,
a css text example: "transform:translate(10 10);",
it doesn't work.
did i got wrong example?

**Comment by sammycage** [comment] 2024-11-22 07:20
You're not doing anything wrong! The issue is that the `transform` attribute isn't considered a presentational attribute in the SVG 1.1 spec. This means it can't be used directly as a CSS property like in your example.

**Comment by zhaoxiangfeng** [comment] 2024-11-22 07:42
> You're not doing anything wrong! The issue is that the `transform` attribute isn't considered a presentational attribute in the SVG 1.1 spec. This means it can't be used directly as a CSS property like in your example.
oh,i see.i will use other ways to instead this function.
it is almost the weekend,have a good time!
